Remove iter_array_chunks feature
error[E0554]: `#![feature]` may not be used on the stable release channel
The `array_chunks` method has been stabilized, so we no longer need
to enable the `iter_array_chunks` feature.  Also, rewrite the `parse_xyz`
function to use three calls to `nums.next()` rather than
`array_chunks`.